# Syntax reference for this file:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: sphinx
on: [push, pull_request]

# https://gist.github.com/c-bata/ed5e7b7f8015502ee5092a3e77937c99
jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      # ^-- This gives info on matrix testing.
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # I don't know where the "run" thing is documented.
      - name: Install dependencies
        id: install-dep
        run: |
          pip install -r source/sphinxrequires.txt
      - name: Install Module
        run: |
          pip install .
      - name: Clean Documentation
        run: |
          make clean
      - name: Build Sphinx docs
        if: success()
        run: |
          sphinx-build -M html source docs

      # https://github.com/marketplace/actions/github-pages
      #- if: success()
      #  uses: crazy-max/ghaction-github-pages@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    target_branch: gh-pages
      #    build_dir: _build/html/

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html/


# This action probably does everything for you:
# https://github.com/marketplace/actions/sphinx-build
